version: '3.7'
networks:
    bore:
        name: bore
        driver: bridge
    nginx-proxy:
        name: nginx-proxy
        driver: bridge

services:

    bore-nginx:
        build: .
        environment:
            - VIRTUAL_HOST=${BORE_HOST}
            - LETSENCRYPT_HOST=${BORE_HOST}
        ports:
            - ${NGINX_PORT:-80}:80
        networks:
            - bore
            - nginx-proxy

    bore-server:
        image: ekzhang/bore
        command: server --min-port ${BORE_MIN_PORT:-7000}
        ports:
            - 7835:7835
        environment:
            - BORE_SECRET=${BORE_SECRET}
        networks:
            - bore
