networks:
    bore:
        name: bore
        driver: bridge
    nginx-proxy:
        name: nginx-proxy
        driver: bridge

services:

    bore-nginx:
        image: likesistemas/bore-server:latest
        build: ./nginx/
        environment:
            - BORE_HOST=${BORE_SERVER_HOST:-bore-server}
        ports:
            - ${NGINX_PORT:-80}:80
        restart: always
        networks:
            - bore
            - nginx-proxy

    bore-server:
        build:
            context: .
        ports:
            - 7835:7835
        restart: always
        environment:
            - BORE_SECRET=${BORE_SECRET}
            - BORE_MIN_PORT=${BORE_MIN_PORT:-7000}
        networks:
            - bore
