networks:
    bore:
        driver: bridge

services:
    bore-nginx:
        image: ghcr.io/${GITHUB_REPOSITORY:-username/repo-name}/bore-nginx:latest
        environment:
            - BORE_HOST=${BORE_SERVER_HOST:-bore-server}
            - DNS_RESOLVER=${DNS_RESOLVER:-127.0.0.11}
        ports:
            - ${NGINX_PORT:-80}:80
            - ${BORE_PORT:-7835}:7835
        restart: always
        networks:
            - bore

    bore-server:
        image: ekzhang/bore
        restart: always
        init: true
        command: server
        environment:
            - BORE_SECRET=${BORE_SECRET}
            - BORE_MIN_PORT=${BORE_MIN_PORT:-7000}
            - BORE_MAX_PORT=${BORE_MAX_PORT:-8000}
        networks:
            - bore
