services:
  bore-router:
    image: ghcr.io/beautyfree/bore-nginx/bore-nginx:0.0.14
    restart: always
    networks:
      - dokploy-network
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.bore-router.rule=HostRegexp(`^.+\.bore\.tacticlaunch\.com$`)'
      - 'traefik.http.routers.bore-router.tls=true'
      - 'traefik.http.routers.bore-router.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.bore-router.tls.domains[0].main=bore.tacticlaunch.com'
      - 'traefik.http.routers.bore-router.tls.domains[0].sans=*.bore.tacticlaunch.com'
      - 'traefik.http.services.bore-router.loadbalancer.server.port=80'

  bore-server:
    image: ekzhang/bore
    restart: always
    init: true
    command: server
    environment:
      - BORE_SECRET=${BORE_SECRET}
      - BORE_MIN_PORT=${BORE_MIN_PORT:-7000}
      - BORE_MAX_PORT=${BORE_MAX_PORT:-8000}
    ports:
      - '7835:7835'
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
